* Git Repositories

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git config -e

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "Orgmode.org"]
        url = git://orgmode.org/org-mode.git
        fetch = +refs/heads/*:refs/remotes/Orgmode.org/*
[branch "master"]
        remote = Orgmode.org
        merge = refs/heads/master
[remote "ox-odt"]
        url = git://repo.or.cz/org-mode/cv.git
        fetch = +refs/heads/*:refs/remotes/ox-odt/*
[remote "origin"]
        url =  git@github.com:kjambunathan/org-mode.git
        fetch = +refs/heads/*:refs/remotes/origin/*
#+END_EXAMPLE

* State of the repositories at the start of merge

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline ox-odt/master
f0f93716ce9de71dc904887c066e03644c795545 (ox-odt/master) ox-odt.el: Add support for JabRef

kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline Orgmode.org/master
912a385518bcf2e320cc161d573ad329111de6c7 (origin/master, Orgmode.org/master, Orgmode.org/HEAD) org-agenda: Support for dimming local to each agenda.

kjambunathan@debian:~/src/ox-odt$ git merge-base ox-odt/master Orgmode.org/master
40ef7af622cb461527555538965b7a6a023e76d2

kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline 40ef7af622cb461527555538965b7a6a023e76d2
40ef7af622cb461527555538965b7a6a023e76d2 (tag: my-common-ancestor) org-element: Elements can accept multiple secondary strings
#+END_EXAMPLE


* Ongoing state of the merge

Patches that are to be merged are in the root directory.

Patches that have already been merged are in "done/" subdirectory

* Commits to lisp/ox-odt.el on Orgmode.org, since I forked 

(Common ancestor: 40ef7af622cb461527555538965b7a6a023e76d2)

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git log --reverse --format=oneline my-common-ancestor..Orgmode.org/master -- lisp/ox-odt.el 

fd8c843692e4c487bd03ed0d71b0bac69112b335 ox-odt: Fix bugs in metadata generation
16cea3d7b74e34945355cf434a684890f4c52cb2 ox: Remove `comment' special value for `org-export-with-creator'
e9fd19968b69f3acd102c393336d9d93a72de624 ox: Always insert creator in metadata
79c0aa21ca2657f2ea7272040bce3ff4754bab1b ox: Remove #+KEYWORD and #+DESCRIPTION
a780080fcf38ca6412658323eae9367a17a12bdf ox: Add #+SUBTITLE property in some backends
459033265295723cbfb0fccb3577acbfdc9d0285 Export back-ends: Use `org-export-get-reference'
e0567c9cacc3a13d21a24ba3058d653a335ae9cb Export back-ends: Use `org-export-file-uri'
aad7dd24864f3ce988a67061a391d85e649aa375 ox-odt: Fix bug links without labels.
8e89c0e3b40bb2a140bbbb85def17b1c190eb158 ox-odt: Allow attaching SVG images by default
690e25d9323276ccf013197c71619dbfe1382baa ox-odt: Fix defcustom keywords
d81e6b52b7a02bb3401f2f17dedc746b63eeecc7 Backport commit 6711a21 from Emacs master branch
c115c7b4e86b68fe4f903636252a8b22b46a044f org-compat: Use different font-lock-ensure alias
0cec91d0392c06cc6504b1cbd63d0a8fd3974789 Backport commit b884ff3 from Emacs master branch
6b04312e85f04219aeaa7c7f9669a51ec2cbec17 Backport commit 96794d2 from Emacs master branch
6f9184a294e4e7914041c2ae42ef147d11e9ebec Merge branch 'maint' into backport-master
3a81c7ee6f392463db1db4b3e77a0e0411032382 Backport commit 0c856a2 from Emacs master branch
8d00cd896614a6e794765bdcfc7ee9bedd6dc075 ox-odt: Fix footnote export
17a225621c73b4990bd4458924a249aa0a11650e ox-odt: Small refactoring
5adb8bcfa2d3611eaa6c69aab23103e60d28bd57 ox-odt: Tiny fix
c290921a0d3a90d7efb702e89c955421a6090116 ox-odt: Prevent internal links to target table of contents
c86a10b0bcc930379ebc9364e6e9e22ba082a64f Backport commit 284c470 from Emacs master branch
cc0d491739b6c81282dfd86330f646d3e4e92b60 Backport commit ab11a1c from Emacs master branch
4ca1179c9e9c707267ac3738cc7c8442001b204b ox-odt: Use lexical binding
07e16c2fc5687de5e1761bbf4ba3cf1777de15eb Use setq-local and defvar-local.
54318add34f09ff39d3fd034a4c1a89f60fd8759 Change export block syntax
6bc48c5f4124a56b84e87b04020d255d126d2aa8 Update copyright years
6345de2d05412113954efd6881d7d5e5a29586cd Merge branch 'maint'
a4edee4069007591d0159df518936a2699123c6e org-compat: Update font-lock-ensure alias
23ca3fa100c2fd8e3dab839fba5ca205e32d83d5 Merge branch 'maint'
07ee690dce504c6082d5ebbe90e6cf4478e07586 ox-odt: Fix End of file during parsing error
16dbf6ded6f79c0b7797856004b0ebc5fe49fb04 Merge branch 'maint'
21ef130752bdfb0ae841d53dd1458b5a505236af ox-odt: Fix styles location
b2411769cfa3bd5267b08bb266ac502ec58a786e Merge branch 'maint'
af8e3d84ee18609a83e03af44efc5601700d57fc ox: Provide offset to [+-]n in SRC/EXAMPLE export
0ac099a6f8f58770c583de450a665be755a95b60 Remove final parts of XEmacs compatibility code
ee7aa9878f4ae76fce63be763e7825c654719f1b Deprecate `org-no-warnings' in favor of `with-no-warnings'
b2091f6d75ee10928b12d115dc3286e479f303d5 Move obsolete declarations into "org-compat.el"
72461eaeaf0317a211a01d31f85eeed0d0ab7b0a Use `string-match-p' instead of `org-string-match-p'
2b99f910e1c0d1f4701772f9bedf66894e16c403 ox-odt: Use cl-lib
c4da20a2f33a3e859df6a5d9d8f95e3a46e453ec Silence byte-compiler
67c29aa1e8b1ffd4dcfb0d86822e42a8139cf203 ox-odt: Remove obnoxious messages when compiling library
ab21e2b72d504c13e035757a4765d02f8e938968 Use file-name-extension where appropriate
48e7f17bc6df8bf7d6ed8d34c849beefb7262dfc Use assq instead of assoc with quoted symbols
140aacbf2f57e207a33417bb446060de52a4b312 Use ‘eq’ instead of ‘equal’ for symbols
d9070419119cf6b19f2f471aa2eb81ec3d9b0d0f Change :version in defcustoms from "25.1" to "25.2"
0c0bc8419093a1034ae5e1cdb2a63b04ae8267fc Change "Org-mode" into "Org mode"
1a88cf920e5090c311f77ba3f74183aa51253fb5 org-element: Improve support for pseudo objects and elements
73694b21d7233c88bbd6e67eefaf8f4c321e4863 ox-odt.el: Fix LaTeX formulae in opendocument exports
b7cb9b54d53fa4e246138791ccc863ae8f927860 Backport commit eeecac7 from Emacs
5ffb373a2ca6833617e344154c3dc1b877ec4784 Implement `org-export-insert-image-links'
3469830e3d95c6176fb91017463c5ef4140dd1c0 ox-odt: Fix typo
713f785017e908333caddd244fcc685745e78539 Update copyright years
0d3683f2cd5490f213b471385d76479f819e2f41 Merge branch 'maint'
1749dfe091308d33799de20fb839cb3604afacc2 ox-odt: Fix verse environment
400d46e547d265623e8af75dc436b67526def04c Merge branch 'maint'
7c710f6f57ab7dcc539511cc9c51ee350a966fce Change :version in defcustoms from "25.2" to "26.1"
7278899697ef146ed7048245a9a75a09922f46e0 Merge branch 'maint'
7b065b1d0a0811304a7599b9feb1c239df1a48db ox-odt: Include #+latex_header when converting LaTeX to PNG
09e61233ed5a24687e20b7dc18a1c985d423fb24 Merge branch 'maint'
#+END_EXAMPLE


* Commits to lisp/ox-odt.el on Orgmode.org since I forked 

(Common ancestor: 40ef7af622cb461527555538965b7a6a023e76d2)

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git log --reverse --pretty=format:%H my-common-ancestor..Orgmode.org/master -- lisp/ox-odt.el 

fd8c843692e4c487bd03ed0d71b0bac69112b335
16cea3d7b74e34945355cf434a684890f4c52cb2
e9fd19968b69f3acd102c393336d9d93a72de624
79c0aa21ca2657f2ea7272040bce3ff4754bab1b
a780080fcf38ca6412658323eae9367a17a12bdf
459033265295723cbfb0fccb3577acbfdc9d0285
e0567c9cacc3a13d21a24ba3058d653a335ae9cb
aad7dd24864f3ce988a67061a391d85e649aa375
8e89c0e3b40bb2a140bbbb85def17b1c190eb158
690e25d9323276ccf013197c71619dbfe1382baa
d81e6b52b7a02bb3401f2f17dedc746b63eeecc7
c115c7b4e86b68fe4f903636252a8b22b46a044f
0cec91d0392c06cc6504b1cbd63d0a8fd3974789
6b04312e85f04219aeaa7c7f9669a51ec2cbec17
6f9184a294e4e7914041c2ae42ef147d11e9ebec
3a81c7ee6f392463db1db4b3e77a0e0411032382
8d00cd896614a6e794765bdcfc7ee9bedd6dc075
17a225621c73b4990bd4458924a249aa0a11650e
5adb8bcfa2d3611eaa6c69aab23103e60d28bd57
c290921a0d3a90d7efb702e89c955421a6090116
c86a10b0bcc930379ebc9364e6e9e22ba082a64f
cc0d491739b6c81282dfd86330f646d3e4e92b60
4ca1179c9e9c707267ac3738cc7c8442001b204b
07e16c2fc5687de5e1761bbf4ba3cf1777de15eb
54318add34f09ff39d3fd034a4c1a89f60fd8759
6bc48c5f4124a56b84e87b04020d255d126d2aa8
6345de2d05412113954efd6881d7d5e5a29586cd
a4edee4069007591d0159df518936a2699123c6e
23ca3fa100c2fd8e3dab839fba5ca205e32d83d5
07ee690dce504c6082d5ebbe90e6cf4478e07586
16dbf6ded6f79c0b7797856004b0ebc5fe49fb04
21ef130752bdfb0ae841d53dd1458b5a505236af
b2411769cfa3bd5267b08bb266ac502ec58a786e
af8e3d84ee18609a83e03af44efc5601700d57fc
0ac099a6f8f58770c583de450a665be755a95b60
ee7aa9878f4ae76fce63be763e7825c654719f1b
b2091f6d75ee10928b12d115dc3286e479f303d5
72461eaeaf0317a211a01d31f85eeed0d0ab7b0a
2b99f910e1c0d1f4701772f9bedf66894e16c403
c4da20a2f33a3e859df6a5d9d8f95e3a46e453ec
67c29aa1e8b1ffd4dcfb0d86822e42a8139cf203
ab21e2b72d504c13e035757a4765d02f8e938968
48e7f17bc6df8bf7d6ed8d34c849beefb7262dfc
140aacbf2f57e207a33417bb446060de52a4b312
d9070419119cf6b19f2f471aa2eb81ec3d9b0d0f
0c0bc8419093a1034ae5e1cdb2a63b04ae8267fc
1a88cf920e5090c311f77ba3f74183aa51253fb5
73694b21d7233c88bbd6e67eefaf8f4c321e4863
b7cb9b54d53fa4e246138791ccc863ae8f927860
5ffb373a2ca6833617e344154c3dc1b877ec4784
3469830e3d95c6176fb91017463c5ef4140dd1c0
713f785017e908333caddd244fcc685745e78539
0d3683f2cd5490f213b471385d76479f819e2f41
1749dfe091308d33799de20fb839cb3604afacc2
400d46e547d265623e8af75dc436b67526def04c
7c710f6f57ab7dcc539511cc9c51ee350a966fce
7278899697ef146ed7048245a9a75a09922f46e0
7b065b1d0a0811304a7599b9feb1c239df1a48db
09e61233ed5a24687e20b7dc18a1c985d423fb24
#+END_EXAMPLE


* Commits on my personal repository, since I forked

#+BEGIN_EXAMPLE

kjambunathan@debian:~/src/ox-odt$ git log --reverse --format=oneline my-common-ancestor..ox-odt/master

758cc3ac9659969a98dd0c7122eec6c3746c02c9 ox-odt.el: Revert to 8ad20618d1ff574406dc1ad6e998f400
17a9e8f6dc4c286fb949108ea81e11ae68950762 Revert "ox-odt.el (org-odt-table-style-format): Use %s for inserting the rel-width property as a string"
a58ea74c76fbf311a6d4becca4b7aceb0efc556c Revert "Fix ox-odt bugs"
b433092f5769031b4605221cea0dc8f9c30d905e ox-odt: Support for typesetting Description lists as in LaTeX
103e0c3979a0c30511c2ede8191323798ba8b5f3 ox-odt.el: Fix handling of ODT attributes
70cb10a00c3f1c403a09ea8212d9b61e6d695b65 ox-odt.el: Support for pagebreaks, custom paragraph styles.
9c16b38824c4e11464ebb3c2d42e276fec85a57c ox-odt.el: Specify cell widths using `:widths' attribute
be7c7512c7b56dff7d9294104c42c45fc6f8644c ox-odt.el: Don't allow table row to split across pages
89ee3445d8aec1e5e1e88389697a1b37e4ea3d46 ox-odt.el: Support hrule and table attributes in list tables
4ffc6188ab4c391da4fa1bbadc33521409e98a73 contrib/lisp/ox-freemind.el: Require cl
2299b2c09aa114a643f2713034e2cb024000fac6 ox-odt.el: Explicitly set coding system of XML files to 'utf-8
fd28aa3d325c343f8b2c7cb9424782fadc322b54 ox-odt.el: Fix issues seen with ODT files having multiple images
c2cb24458f7fae6f7b8052dd2239294fcb26657d ox-odt.el: Fix paths of data and styles directories
3424dfc9c48fe38682b67de27a822825da27807d ox-odt.el (generated-autoload-file): Don't set it
9bb3fb55de2c0e9a8139fa6a777f4513f9f0ed6a ox-odt.el (org-odt-schema-dir-list): Add git and elpa paths
429f259818c8cd1ac5f3328985c13687ce46883f ox-odt.el: Fix cell borders
a4bcd8d518cd2cc1a90d54762ac7a190ddfe19ad ox-odt.el: Cope with empty title
a2c4369a7598c15094acb1e85309f42c85b4e93d ox-odt.el: Support for page nos. etc as part of xref-es
7b2d1c938a5eb5bcba07ab9573bd05cfeade5cc7 Use a "OrgPageBreakDefault" as default PAGEBREAK style
315dba1624e59d6a7d0658054273d80b83771a84 ox-odt.el: Support for custom para style within SPECIAL-BLOCKs
4a3d7e91936962f0d45fdf4f36ac79627fa9b032 Correctly check for standard-value of `org-odt-caption-and-xref-settings'.
2234655d7edd9742db6671af830c1990d1a04ba6 ox-odt: Use `org-element-lineage' instead of `org-export-get-genealogy'
39a722271d67275530ecef5001f2adb91bede2f0 ox-odt: Fix invocation of `org-format-latex'
ebec71a4f2f188aee8286965633d39cbc5583d0a ox-odt.el (org-odt-special-block): Preserve case
fd97fcd5a7a7259a055eef25f72633493d4affe9 ox-odt.el: Remove some export options associated to variables
1811d1a09e641a5738bf3a11950b4dad0ea7da38 ox-odt.el: Use options instead of hard-coded variables
7d1711266a7879736202b0d1f8fb04b8eabdf3f3 ox-odt: Implement `org-odt-format-{headline, inlinetask}-default-function'
157bfc83140f14d6f2fa8bc4fee0eb3a94570a8b ox-odt.el: Misc. changes
4b228baf822f06a224e7d3bcc4507b35d56ca119 ox-odt.el: Fix exporting radio link with missing radio target
c9413bff9050ae797cf163c173b68bea59906246 ox-odt.el (org-odt-link): Use `org-export-custom-protocol-maybe'.
5ecf5cf9e9ad13248b3a3e876f5e4d4675f47d3a ox-odt.el: Support `:with-title'
48c3d6a55fa03e03289a422ddf100d877b50d81b ox-odt.el: Support `:with-title'
5179ee82a8da523a473a429005ca8d34d05a85ba ox-odt.el: Enumerate footnotes based on body text
a2204248776dfbc23a9296881a24b04ccb497c21 ox-odt.el: Update copyright years
a8f8b4f3f15db8652b4a43526253d2746b6094f5 ox-odt.el: Use scope param in org-export-footnote-* calls
7f27f738e52334115a0fc8cb2b6078beb710ae92 ox-odt.el (org-odt-link): Fix custom link handling
1afc7309750e6f8daf8d44b357b80d18ab16f037 ox-odt.el (org-odt-template): Don't create empty paragraphs
c80c904ad4b63fee0c6bfcb2092314d4b6f32920 ox-odt.el: Preserve white space when converting LaTeX code.
a8a675e9326c7d33d55c000d29c91a7eb7f7736c ox-odt.el: Fix leading whitespace
8d48a1d882dba18cf78b11b934be7b6b626ba6a8 org-element: Add basic citation support
7599897f933766c68420a3035caeb7cad66f54d4 Remove @ from the :key property of citations
f0f93716ce9de71dc904887c066e03644c795545 ox-odt.el: Add support for JabRef
#+END_EXAMPLE

* Commit ids on this repository, after the merge

#+BEGIN_VERSE
kjambunathan@debian:~/src/ox-odt$ git log --reverse --format=oneline Orgmode.org/master..
9d81860593dd12a8ee6ce9637fe4e4b92d4cf19e Preparing to merge my ox-odt changes to Orgmode.org master
06bfe66aec27459994c3eb5e40db0cec40823f17 ox-odt.el: Revert to 8ad20618d1ff574406dc1ad6e998f400
c06478c9d99be23ecfda9b33edb33bad860659fd Revert "ox-odt.el (org-odt-table-style-format): Use %s for inserting the rel-width property as a string"
8071ce913c1a34b1cbfed4920066d4d2b714c68f Revert "Fix ox-odt bugs"
be9840d204e37939b354c2361e1a6cbee2bd474a ox-odt: Support for typesetting Description lists as in LaTeX
f1e4f96edc0228fdbcb7db544cf00d72530ed7f1 ox-odt.el: Fix handling of ODT attributes
92f0ee559d166cb9539f17134373f50cd332cab3 ox-odt.el: Support for pagebreaks, custom paragraph styles.
6fc6c7468473a7e03f18cbd9fe53cb902c9770ef ox-odt.el: Specify cell widths using `:widths' attribute
4578504b92175733bde483a2e13f26691852d752 ox-odt.el: Don't allow table row to split across pages
271212243d8923297c494588c9ef5a7c1c7fdb8d ox-odt.el: Support hrule and table attributes in list tables
4fa8daa03c6461c15a7990a2209cbb2a88eed436 contrib/lisp/ox-freemind.el: Require cl
40bfe609ed5e71ef1ee3365eedb0b363135fe386 ox-odt.el: Explicitly set coding system of XML files to 'utf-8
8072610932d29be81bd1af3a76b2da504d969c66 ox-odt.el: Fix issues seen with ODT files having multiple images
65d7400a9472d175fd83107564172c9d6d59ee74 ox-odt.el: Fix paths of data and styles directories
2d25f217e11a2bf22837acad082f6d80883238fe ox-odt.el (generated-autoload-file): Don't set it
b5afbc2f459bc06cc144649848efa659bf1ee606 ox-odt.el (org-odt-schema-dir-list): Add git and elpa paths
c51f4ba71ccaa08b8723b2acfe77ba9d46d12a53 ox-odt.el: Fix cell borders
befa2c8b3d7dbefb5d539c4c17624d8899d56870 ox-odt.el: Cope with empty title
d0fe9e23b53dae59e643d6f27d69f7b1f3c17d77 ox-odt.el: Support for page nos. etc as part of xref-es
1bf39dfd76f8cd29b04495fe698d6b3dab126311 Use a "OrgPageBreakDefault" as default PAGEBREAK style
b2a15b5c383624e1a2f77f57ceae95d43190b586 ox-odt.el: Support for custom para style within SPECIAL-BLOCKs
99008bbb89f5e3908ea78a6eacee7710cc461168 Correctly check for standard-value of `org-odt-caption-and-xref-settings'.
82ea45464dfc7dea63c8a4e4c0e44c2bfd3e987f ox-odt: Use `org-element-lineage' instead of `org-export-get-genealogy'
d105d1e5746ec69778648288c1b5a5ccdff79651 ox-odt: Fix invocation of `org-format-latex'
19723fd47abef8272477e91e17489ca7f3842825 ox-odt.el (org-odt-special-block): Preserve case
4b8ffd3c20b671bae50b8728b3ca74bc283a4308 ox-odt.el: Remove some export options associated to variables
0a7ced81c391e20c857d8b5ce8eb912bd54e5965 ox-odt.el: Use options instead of hard-coded variables
ee2d0e43aeebe647b61a7bb9315630c0eeac8ebd ox-odt: Implement `org-odt-format-{headline, inlinetask}-default-function'
d6e349ec787755a8fdbd4c35d0041383842c056a ox-odt.el: Misc. changes
cb1f884ee690717ed0194804c7bad2263f05cfc9 ox-odt.el: Fix exporting radio link with missing radio target
5b1989cba2acb4f4dfbae0ac841331e19de35c37 ox-odt.el (org-odt-link): Use `org-export-custom-protocol-maybe'.
11dbb5a3581c95a0b99b30e36963a6ef0b76b36c ox-odt.el: Support `:with-title'
4c40f0109f059a00e815841d88c14c9c1aec2f1d ox-odt.el: Support `:with-title'
b577fdd5f2aa38506d2c06314b6841b26cb52986 ox-odt.el: Enumerate footnotes based on body text
1d7dd0ab565eea48bbfd287d55138c79e1e412b6 ox-odt.el: Update copyright years
d84859213045a552e12e519c7ed01522d903db88 ox-odt.el: Use scope param in org-export-footnote-* calls
96b4bbb568a473844b8ed1d6180c5eb38af7f157 ox-odt.el (org-odt-link): Fix custom link handling
0f0513e07ef9312e4cdf0cff9de50fd563e5dde6 ox-odt.el (org-odt-template): Don't create empty paragraphs
b5e1d0b85588d81824348f229090525963225a60 ox-odt.el: Preserve white space when converting LaTeX code.
b3eedee14c5665c4102faa3e886d333196df1d15 ox-odt.el: Fix leading whitespace
2922956cd3440484a46b4ef340aab014c2da2e8e org-element: Add basic citation support
fbe3059c74132938b76a553c85599c86cfe82ede Remove @ from the :key property of citations
7dd98d9c8db6f0b4a1d241e60be600e02239e7a1 org-element: Fix `org-element-citation-interpreter'
7d19a295bd9b356f377af9a747d82230ebd0066a org-element: Change syntax for citation keys
bab686d56560cb1dde78bdf329cede7791b6a636 org-element: Allow any word character in citation keys
2a357f2f7da8d5b0eb5424509b8948995f9fa04f org-element: Parse multi citations
3a6ae8034e55b9dd150ae8e78f72c9e10bd0197c org-element: Split citations and citation-references objects
8ae8017afa5224fd7a9f03ca1081dbdd4780fff3 org-element: Fix typo
5f5cd2ee77d3de636a7f7a005f871f0768accc4d org-element: Get rid of compiler warning
905d6ba8034bc5b1b2fa052d2197e0edce8d4896 ox-odt.el: Add support for JabRef
df47e82848379451f51a2d156d169b30f0186e53 lisp/ox-odt.el: Use lexical binding
32618d8025392b411b21062087e7b37b87a254bf lisp/ox-odt.el: Use `cl-lib'
9ddb3a9f73c9796d1925abe128e50a610386d129 lisp/ox-odt.el: Add kludge to get past compilation errors
ea8415d73f545671abee66ee6c7e14dd1cd55981 * lisp/ox-odt.el: Remove `:export-block' from backend definition
b3c2eebf374ff841abea972ff7c090bddc273913 lisp/ox-odt.el: Manually merge some changes from Orgmode.org master
#+END_VERSE


