* Git Repositories

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git config -e

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "Orgmode.org"]
        url = git://orgmode.org/org-mode.git
        fetch = +refs/heads/*:refs/remotes/Orgmode.org/*
[branch "master"]
        remote = Orgmode.org
        merge = refs/heads/master
[remote "ox-odt"]
        url = git://repo.or.cz/org-mode/cv.git
        fetch = +refs/heads/*:refs/remotes/ox-odt/*
[remote "origin"]
        url =  git@github.com:kjambunathan/org-mode.git
        fetch = +refs/heads/*:refs/remotes/origin/*
#+END_EXAMPLE

* State of the repositories at the start of merge

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline ox-odt/master
f0f93716ce9de71dc904887c066e03644c795545 (ox-odt/master) ox-odt.el: Add support for JabRef

kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline Orgmode.org/master
912a385518bcf2e320cc161d573ad329111de6c7 (origin/master, Orgmode.org/master, Orgmode.org/HEAD) org-agenda: Support for dimming local to each agenda.

kjambunathan@debian:~/src/ox-odt$ git merge-base ox-odt/master Orgmode.org/master
40ef7af622cb461527555538965b7a6a023e76d2

kjambunathan@debian:~/src/ox-odt$ git log -1 --pretty=oneline 40ef7af622cb461527555538965b7a6a023e76d2
40ef7af622cb461527555538965b7a6a023e76d2 (tag: my-common-ancestor) org-element: Elements can accept multiple secondary strings
#+END_EXAMPLE


* Ongoing state of the merge

Patches that are to be merged are in the root ~./todo[N]/~ directory.

Patches that have already been merged are in ~./done[N]~ directory

* Commits that are exclusive to this branch

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/org-mode-ox-odt$ git describe
release_9.1.14-157-gf8c51feb6
#+END_EXAMPLE

#+BEGIN_EXAMPLE
kjambunathan@debian:~/src/org-mode-ox-odt$ git log --reverse --format=oneline my-common-ancestor.. -- lisp/ox-odt.el >> notes/README.org
#+END_EXAMPLE

fd8c843692e4c487bd03ed0d71b0bac69112b335 ox-odt: Fix bugs in metadata generation
16cea3d7b74e34945355cf434a684890f4c52cb2 ox: Remove `comment' special value for `org-export-with-creator'
e9fd19968b69f3acd102c393336d9d93a72de624 ox: Always insert creator in metadata
79c0aa21ca2657f2ea7272040bce3ff4754bab1b ox: Remove #+KEYWORD and #+DESCRIPTION
a780080fcf38ca6412658323eae9367a17a12bdf ox: Add #+SUBTITLE property in some backends
459033265295723cbfb0fccb3577acbfdc9d0285 Export back-ends: Use `org-export-get-reference'
e0567c9cacc3a13d21a24ba3058d653a335ae9cb Export back-ends: Use `org-export-file-uri'
aad7dd24864f3ce988a67061a391d85e649aa375 ox-odt: Fix bug links without labels.
8e89c0e3b40bb2a140bbbb85def17b1c190eb158 ox-odt: Allow attaching SVG images by default
690e25d9323276ccf013197c71619dbfe1382baa ox-odt: Fix defcustom keywords
d81e6b52b7a02bb3401f2f17dedc746b63eeecc7 Backport commit 6711a21 from Emacs master branch
c115c7b4e86b68fe4f903636252a8b22b46a044f org-compat: Use different font-lock-ensure alias
0cec91d0392c06cc6504b1cbd63d0a8fd3974789 Backport commit b884ff3 from Emacs master branch
6b04312e85f04219aeaa7c7f9669a51ec2cbec17 Backport commit 96794d2 from Emacs master branch
6f9184a294e4e7914041c2ae42ef147d11e9ebec Merge branch 'maint' into backport-master
3a81c7ee6f392463db1db4b3e77a0e0411032382 Backport commit 0c856a2 from Emacs master branch
8d00cd896614a6e794765bdcfc7ee9bedd6dc075 ox-odt: Fix footnote export
17a225621c73b4990bd4458924a249aa0a11650e ox-odt: Small refactoring
5adb8bcfa2d3611eaa6c69aab23103e60d28bd57 ox-odt: Tiny fix
c290921a0d3a90d7efb702e89c955421a6090116 ox-odt: Prevent internal links to target table of contents
c86a10b0bcc930379ebc9364e6e9e22ba082a64f Backport commit 284c470 from Emacs master branch
cc0d491739b6c81282dfd86330f646d3e4e92b60 Backport commit ab11a1c from Emacs master branch
4ca1179c9e9c707267ac3738cc7c8442001b204b ox-odt: Use lexical binding
07e16c2fc5687de5e1761bbf4ba3cf1777de15eb Use setq-local and defvar-local.
54318add34f09ff39d3fd034a4c1a89f60fd8759 Change export block syntax
6bc48c5f4124a56b84e87b04020d255d126d2aa8 Update copyright years
6345de2d05412113954efd6881d7d5e5a29586cd Merge branch 'maint'
a4edee4069007591d0159df518936a2699123c6e org-compat: Update font-lock-ensure alias
23ca3fa100c2fd8e3dab839fba5ca205e32d83d5 Merge branch 'maint'
07ee690dce504c6082d5ebbe90e6cf4478e07586 ox-odt: Fix End of file during parsing error
16dbf6ded6f79c0b7797856004b0ebc5fe49fb04 Merge branch 'maint'
21ef130752bdfb0ae841d53dd1458b5a505236af ox-odt: Fix styles location
b2411769cfa3bd5267b08bb266ac502ec58a786e Merge branch 'maint'
af8e3d84ee18609a83e03af44efc5601700d57fc ox: Provide offset to [+-]n in SRC/EXAMPLE export
0ac099a6f8f58770c583de450a665be755a95b60 Remove final parts of XEmacs compatibility code
ee7aa9878f4ae76fce63be763e7825c654719f1b Deprecate `org-no-warnings' in favor of `with-no-warnings'
b2091f6d75ee10928b12d115dc3286e479f303d5 Move obsolete declarations into "org-compat.el"
72461eaeaf0317a211a01d31f85eeed0d0ab7b0a Use `string-match-p' instead of `org-string-match-p'
2b99f910e1c0d1f4701772f9bedf66894e16c403 ox-odt: Use cl-lib
c4da20a2f33a3e859df6a5d9d8f95e3a46e453ec Silence byte-compiler
67c29aa1e8b1ffd4dcfb0d86822e42a8139cf203 ox-odt: Remove obnoxious messages when compiling library
ab21e2b72d504c13e035757a4765d02f8e938968 Use file-name-extension where appropriate
48e7f17bc6df8bf7d6ed8d34c849beefb7262dfc Use assq instead of assoc with quoted symbols
140aacbf2f57e207a33417bb446060de52a4b312 Use ‘eq’ instead of ‘equal’ for symbols
d9070419119cf6b19f2f471aa2eb81ec3d9b0d0f Change :version in defcustoms from "25.1" to "25.2"
0c0bc8419093a1034ae5e1cdb2a63b04ae8267fc Change "Org-mode" into "Org mode"
1a88cf920e5090c311f77ba3f74183aa51253fb5 org-element: Improve support for pseudo objects and elements
73694b21d7233c88bbd6e67eefaf8f4c321e4863 ox-odt.el: Fix LaTeX formulae in opendocument exports
b7cb9b54d53fa4e246138791ccc863ae8f927860 Backport commit eeecac7 from Emacs
5ffb373a2ca6833617e344154c3dc1b877ec4784 Implement `org-export-insert-image-links'
3469830e3d95c6176fb91017463c5ef4140dd1c0 ox-odt: Fix typo
713f785017e908333caddd244fcc685745e78539 Update copyright years
0d3683f2cd5490f213b471385d76479f819e2f41 Merge branch 'maint'
1749dfe091308d33799de20fb839cb3604afacc2 ox-odt: Fix verse environment
400d46e547d265623e8af75dc436b67526def04c Merge branch 'maint'
7c710f6f57ab7dcc539511cc9c51ee350a966fce Change :version in defcustoms from "25.2" to "26.1"
7278899697ef146ed7048245a9a75a09922f46e0 Merge branch 'maint'
7b065b1d0a0811304a7599b9feb1c239df1a48db ox-odt: Include #+latex_header when converting LaTeX to PNG
09e61233ed5a24687e20b7dc18a1c985d423fb24 Merge branch 'maint'
9d81860593dd12a8ee6ce9637fe4e4b92d4cf19e Preparing to merge my ox-odt changes to Orgmode.org master
06bfe66aec27459994c3eb5e40db0cec40823f17 ox-odt.el: Revert to 8ad20618d1ff574406dc1ad6e998f400
c06478c9d99be23ecfda9b33edb33bad860659fd Revert "ox-odt.el (org-odt-table-style-format): Use %s for inserting the rel-width property as a string"
8071ce913c1a34b1cbfed4920066d4d2b714c68f Revert "Fix ox-odt bugs"
be9840d204e37939b354c2361e1a6cbee2bd474a ox-odt: Support for typesetting Description lists as in LaTeX
f1e4f96edc0228fdbcb7db544cf00d72530ed7f1 ox-odt.el: Fix handling of ODT attributes
92f0ee559d166cb9539f17134373f50cd332cab3 ox-odt.el: Support for pagebreaks, custom paragraph styles.
6fc6c7468473a7e03f18cbd9fe53cb902c9770ef ox-odt.el: Specify cell widths using `:widths' attribute
4578504b92175733bde483a2e13f26691852d752 ox-odt.el: Don't allow table row to split across pages
271212243d8923297c494588c9ef5a7c1c7fdb8d ox-odt.el: Support hrule and table attributes in list tables
40bfe609ed5e71ef1ee3365eedb0b363135fe386 ox-odt.el: Explicitly set coding system of XML files to 'utf-8
8072610932d29be81bd1af3a76b2da504d969c66 ox-odt.el: Fix issues seen with ODT files having multiple images
65d7400a9472d175fd83107564172c9d6d59ee74 ox-odt.el: Fix paths of data and styles directories
2d25f217e11a2bf22837acad082f6d80883238fe ox-odt.el (generated-autoload-file): Don't set it
b5afbc2f459bc06cc144649848efa659bf1ee606 ox-odt.el (org-odt-schema-dir-list): Add git and elpa paths
c51f4ba71ccaa08b8723b2acfe77ba9d46d12a53 ox-odt.el: Fix cell borders
befa2c8b3d7dbefb5d539c4c17624d8899d56870 ox-odt.el: Cope with empty title
d0fe9e23b53dae59e643d6f27d69f7b1f3c17d77 ox-odt.el: Support for page nos. etc as part of xref-es
1bf39dfd76f8cd29b04495fe698d6b3dab126311 Use a "OrgPageBreakDefault" as default PAGEBREAK style
b2a15b5c383624e1a2f77f57ceae95d43190b586 ox-odt.el: Support for custom para style within SPECIAL-BLOCKs
99008bbb89f5e3908ea78a6eacee7710cc461168 Correctly check for standard-value of `org-odt-caption-and-xref-settings'.
82ea45464dfc7dea63c8a4e4c0e44c2bfd3e987f ox-odt: Use `org-element-lineage' instead of `org-export-get-genealogy'
d105d1e5746ec69778648288c1b5a5ccdff79651 ox-odt: Fix invocation of `org-format-latex'
19723fd47abef8272477e91e17489ca7f3842825 ox-odt.el (org-odt-special-block): Preserve case
4b8ffd3c20b671bae50b8728b3ca74bc283a4308 ox-odt.el: Remove some export options associated to variables
0a7ced81c391e20c857d8b5ce8eb912bd54e5965 ox-odt.el: Use options instead of hard-coded variables
ee2d0e43aeebe647b61a7bb9315630c0eeac8ebd ox-odt: Implement `org-odt-format-{headline, inlinetask}-default-function'
d6e349ec787755a8fdbd4c35d0041383842c056a ox-odt.el: Misc. changes
cb1f884ee690717ed0194804c7bad2263f05cfc9 ox-odt.el: Fix exporting radio link with missing radio target
5b1989cba2acb4f4dfbae0ac841331e19de35c37 ox-odt.el (org-odt-link): Use `org-export-custom-protocol-maybe'.
11dbb5a3581c95a0b99b30e36963a6ef0b76b36c ox-odt.el: Support `:with-title'
4c40f0109f059a00e815841d88c14c9c1aec2f1d ox-odt.el: Support `:with-title'
b577fdd5f2aa38506d2c06314b6841b26cb52986 ox-odt.el: Enumerate footnotes based on body text
1d7dd0ab565eea48bbfd287d55138c79e1e412b6 ox-odt.el: Update copyright years
d84859213045a552e12e519c7ed01522d903db88 ox-odt.el: Use scope param in org-export-footnote-* calls
96b4bbb568a473844b8ed1d6180c5eb38af7f157 ox-odt.el (org-odt-link): Fix custom link handling
0f0513e07ef9312e4cdf0cff9de50fd563e5dde6 ox-odt.el (org-odt-template): Don't create empty paragraphs
b5e1d0b85588d81824348f229090525963225a60 ox-odt.el: Preserve white space when converting LaTeX code.
b3eedee14c5665c4102faa3e886d333196df1d15 ox-odt.el: Fix leading whitespace
905d6ba8034bc5b1b2fa052d2197e0edce8d4896 ox-odt.el: Add support for JabRef
df47e82848379451f51a2d156d169b30f0186e53 lisp/ox-odt.el: Use lexical binding
32618d8025392b411b21062087e7b37b87a254bf lisp/ox-odt.el: Use `cl-lib'
9ddb3a9f73c9796d1925abe128e50a610386d129 lisp/ox-odt.el: Add kludge to get past compilation errors
ea8415d73f545671abee66ee6c7e14dd1cd55981 * lisp/ox-odt.el: Remove `:export-block' from backend definition
b3c2eebf374ff841abea972ff7c090bddc273913 lisp/ox-odt.el: Manually merge some changes from Orgmode.org master
24574bbac348ae97b3c0539c75ba7ea4e72f3dd6 lisp/ox-odt.el: Improve list tables
0adf1601c1c38e05a7e3571b9f90510e8a968205 Fix all loose ends with ODT's JabRef exporter
850a66178d104339336cab725bf5755ea66659c8 lisp/ox-odt.el: Support \cite{} fragments
9eea0f138ec591312da3ed57d3761c92d0bb19a2 lisp/ox-odt.el: Generate table of figures, listings and tables.
d471baa13415eceb5bed29ad52a48a28cf8ae4b6 lisp/ox-odt.el: Support document transformation using LibreOffice macros
364281914f0a41e8f0fca8ba4194ac01b47b9f58 * lisp/ox-odt.el (org-odt-transform-processes): Add a new transformer
9148fd363b387c2ba212c2c750b056a4a8c6996c lisp/ox-odt.el: Honor "local" spec in "#+TOC: ..." directive
0b446370bdeac279b65761b550be9ceb3416c568 lisp/ox-odt.el (org-odt-template):  Don't emit empty paragraphs
5c243da2d8b297be68c863177b738564df790fe8 lisp/ox-odt.el: Support column width and sizing of list tables
00c05082e3b80b7463e321ba2426a5a33463731a lisp/ox-odt.el (org-odt--translate-list-tables): Fix regexp
3355089d0a9b442040da30d0d422110532995ab7 * lisp/ox-odt.el: Minor refactoring
dd10d04f2cdfdb0e27155c239a3ac094bb0f2e88 lisp/ox-odt.el: Customize table paragraphs through  `:p-style' attribute
851b588dd80b5d59caa6ea9972cf2e6a54eb3620 lisp/ox-odt.el: In list tables, ignore col alignment cookies
c397ae4f69e2ba2fefd0c4284cdf97c8d834b873 lisp/ox-odt.el: Allow custom paragraph styles for verse blocks
7b2484ed4029a0e2f40514117e606c3cfbee11ca lisp/ox-odt.el: Replace `org-odt-automatic-styles' with `org-odt--automatic-styles'
1329f6524e4f4565a8284d5cc83c1b090a48fb1b Revert "lisp/ox-odt.el: Replace `org-odt-automatic-styles' with `org-odt--automatic-styles'"
f983aa8ba0c55a4cf4376d941f418c7c5d664611 ox-odt.el, ox-jabref.el: Gracefully handle corner cases
06ac3257fbd85a0de9ee635ddb674d87a69b3f31 lisp/ox-odt.el:  Handle case where #+ODT_STYLES_FILE is empty
39b6bc6fa6607b13f9d00e611d04b97bf2369e70 Introduce keywords BIB_FILE and ODT_JABREF_CITATION_STYLE
499057dafc5e0b31d4d48b5bd61bf76b8b7c5a6b lisp/ox-odt.el:  Allow \cite{} in captions
58755fa15ddfeb8d985c916ba8bcb9609085e4c3 lisp/ox-odt.el: Support `#+ODT_AUTOMATIC_STYLES: ...'
1ea275f423493af4d66b1c5c622de9c9d0a00425 lisp/ox-odt.el: Support OpenOffice sections
a11d67b60d5714525db056c3bf71317214f36265 lisp/ox-odt.el: Handle relative filepaths correctly
2fe725dfb1986ce0812f5e9957939c7874930f98 lisp/ox-odt.el: Transclude ODT links
01e3274d5a2e328c824bb9b45ff42e37b893d38f lisp/ox-odt.el: Export to OpenDocument master file with `#+ODT_FILE_EXTENSION: odm'
3b6a2df254135a69acdbe5662aa55dd6a9ad4cc6 lisp/ox-odt.el: Allow customization of headline styles
283c4683c74410553a257ca17e4d14a9a730f140 lisp/ox-odt.el: Improve support for pagebreaks
c049488021621286b835af833ac0be551d9e4e7f lisp/ox-odt.el (org-odt-transform-processes):  New macro "Update All and Break Links"
73389e5eb4a7e09bc12efaa1f04aabe7da2ba6ac * lisp/ox-odt.el (org-odt--read-attribute): Use `cl-case' instead of `case'
bece81cb3b31beed1441fc5c1bb9cdd641b11c1f * lisp/ox-odt.el: Define *common* styles through #+ODT_EXTRA_STYLES: ...
dd0f812d99718cc8191b7cb5625461b82a9fb596 * lisp/ox-odt.el: Simplify creation of tables with custom paragraph styles
f95fa831a89aba237d03406c4be7e72049a42775 * lisp/ox-odt.el: New in buffer option ODT_CONTENT_TEMPLATE_FILE
5e4f6908d458e1422bf7d468b36807ee1206f31b * lisp/ox-odt.el: Fix previous commit
b5475e18adcb28a1d2420a0b9acecdad34baae68 ox-odt: Rationalize paragraph style names used within tables
1093b829b91083a07692305d15941ead3c9911bc * lisp/ox-odt.el (org-odt-table-cell--get-paragraph-styles): When a table specifies both a `:style' and `:p-style" attribute, only the table cells (i.e., cell borders etc) get styled as per the table template.  The paragraphs within the cells get styled *not* based on the template, but by "default" rules.
d791a043724f7d724d15692118777ef1fc7f4b93 * lisp/ox-odt.el: New in buffer option ODT_DISPLAY_OUTLINE_LEVEL
bda0add75d0bf26a4fd0a0db02c3edd61a2f51ec * lisp/ox-odt.el (org-odt-paragraph): Trim whitespace from paragraph contents
97ce8bd2b1ef3011a36ceecc67c4bb92ce9be9fe * lisp/ox-odt.el (org-odt-headline): Minor Re-factoring
f8f75e806fb34c00eda4f20a3f2ae87c969e0f50 * lisp/ox-odt.el (org-odt-headline): Minor refactoring
c1d2f132319aad1846c39215f2cce7387741aeb0 * lisp/ox-odt.el (org-odt-headline): Minor refactoring
bf7b8c1aed5f6e4904da89dfe7b9301803d7018e * lisp/ox-odt.el (org-odt-headline): Explicitly number headlines using a list style
51b8dd673960e621ea9c2f77229c71de967b9eae * lisp/ox-odt.el (org-odt-transform-processes): New macro `Reload'
417081c96e7a28e581c69885123c8a0f132be5b8 * lisp/ox-odt.el: Allow caption and name in list-tables
82f3c3a1924149b2d8942e5330ddfb7736f65610 lisp/ox-odt.el, contrib/lisp/ox-jabref.el: Update library headers
