;;;; odt-d288-1 --- Edit `styles.xml' programmatically -*- lexical-binding: t; coding: utf-8-emacs; -*-

;; Copyright (C) 2022  Jambuanthan K

;; Author: Jambunathan K <kjambunathan@gmail.com>
;; Version:
;; Homepage: https://github.com/kjambunathan/dotemacs
;; Keywords:
;; Package-Requires: ((emacs "24"))

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Edit `styles.xml' programmatically.

;;; Code:

;; (require 'odt-d288)

(load-file "odt-d288.el")

;;; APIs

;;;; API to infer `styles.xml' used by current `org' buffer

(defun kjn-odt-d288/infer-styles-file (backend)
  (let ((file (when-let* (((derived-mode-p 'org-mode))
			  (keywords '(
				      (odt . "ODT_STYLES_FILE")
				      (ods . "ODS_STYLES_FILE")))
			  (STYLES-FILE (map-elt keywords backend)))
		(cdar (org-collect-keywords `(,STYLES-FILE) `(,STYLES-FILE))))))
    (cond
     ((or (not file) (string= file ""))
      (org-odt-get-backend-property backend :styles-file))
     ((file-name-absolute-p file) file)
     (
      (expand-file-name
       file (file-name-directory (buffer-file-name)))))))

(defun kjn-odt-d288/infer-styles-dom (backend)
  (thread-last backend
	       kjn-odt-d288/infer-styles-file
	       (kjn-odt-d288/parse-styles-file backend)))

;;;; API to create custom `styles.xml' from any base styles file, say
;;;; `OrgOdtStyles.xml'.  IOW, this is an API to transform one
;;;; `styles.xml' to another `styles.xml'.

(defun kjn-odt-d288/create-custom-styles-from-default-style (backend odt-styles-file fs)
  (setq fs (thread-last fs
			(seq-map
			 (lexical-let ((i 0))
			   (lambda (it)
			     (list (or (function-documentation it) "??") it))))))
  (let* ((in-file (or odt-styles-file (org-odt-get-backend-property 'odt :styles-file)))
	 (dom (kjn-odt-d288/parse-styles-file backend odt-styles-file)))
    (seq-reduce
     (lexical-let ((i 0))
       (pcase-lambda (`(,acc-tag ,dom) `(,tag ,f))
	 (let* ((prev-tag acc-tag)
		(acc-tag (format "%s--%s" acc-tag tag))
		(dom (funcall f dom))
		(prev-i i))
	   (let* ((out-file (format "%s-%03d-%s.xml"
				    (file-name-sans-extension in-file)
				    (cl-incf i)
				    acc-tag)))
	     (message "Step %03d: `%s' = %S"
		      i
		      out-file
		      `(,f ,(format "%s-%03d-%s.xml"
				    (file-name-sans-extension in-file)
				    prev-i
				    prev-tag)))
	     (thread-last dom
			  (odt-stylesdom:dom->file out-file
						   ;; (not 'prettify)
						   'prettify))

	     (list acc-tag dom)))))
     fs
     (list "" dom))))

;;;; [BONUS] Command to create custom `styles.xml' BASED ON default `OrgOdtStyles.xml'

(defun keiser-odt-d288/gather-styles-and-next-styles-from-styles.xml  ()
  (let* ((dom (kjn-odt-d288/infer-styles-dom 'odt))
         (nodes
          (odt-dom--query dom
			  ;; Look for `style:style' descendant of DOM
			  %//style:style
			  (and
                           ;; ... whose `style:family' is of type
	        	   ;; "paragraph", and 
                           (string= %style:family "paragraph")

                           ;; and which specifies `style:next-style-name'                              
	                   %style:next-style-name
                           )

	        	  ;; ... collect the `style:name' and
	        	  ;; `style:next-style-name' properties of those
	        	  ;; nodes
			  (cons %style:name %style:next-style-name)
                          )))
    (thread-last nodes
	         ;; Sort the above list based on `style:name'
	         (seq-sort
		  (pcase-lambda (`(,a . _) `(,b . _))
		    (string< a b))))))

(defun keiser-odt-d288/tranform-dom-to-the-same-dom (dom)
  "identity"
  dom)


(defun keiser-odt-d288/transform-dom-to-dom-with-next-style-in-paragraph-styles (dom)
  "fix-next-style-of-paragraph-styles"
  (prog1 dom
    (let* (
           (styles-and-next-styles
            ;; Alist generated by running
            ;; `keiser-odt-d288/gather-styles-and-next-styles-from-styles.xml'
            ;; on `next-style-sample.org'
	    '(
              ("First_20_line_20_indent"	 . "First_20_line_20_indent")
              ("Heading"			 . "Text_20_body")
              ("Heading_20_1"		 . "Text_20_body")
              ("Heading_20_10"		 . "Text_20_body")
              ("Heading_20_2"		 . "Text_20_body")
              ("Heading_20_3"		 . "Text_20_body")
              ("Heading_20_4"		 . "Text_20_body")
              ("Heading_20_5"		 . "Text_20_body")
              ("Heading_20_6"		 . "Text_20_body")
              ("Heading_20_7"		 . "Text_20_body")
              ("Heading_20_8"		 . "Text_20_body")
              ("Heading_20_9"		 . "Text_20_body")
              ("Horizontal_20_Line"		 . "Text_20_body")
              ("OrgInlineTaskHeading"	 . "Text_20_body")
              ("Quotations"			 . "Text_20_body")
              ("Subtitle"			 . "Text_20_body")
              ("Text_20_body"		 . "First_20_line_20_indent")
              ("Text_20_body_20_bold"	 . "Text_20_body")
              ("Title"			 . "Subtitle")
              )
            )
	   (p-styles
	    (odt-dom--query dom
			    %_all
			    (and (eq %_tag 'style:style)
				 (string= %style:family "paragraph"))
			    (cons %style:name %_self))))
      (thread-last p-styles
		   (seq-do
		    (pcase-lambda (`(,style-name . ,node))
		      (when-let* ((next-style (map-elt styles-and-next-styles style-name)))
			(dom-set-attribute node 'style:next-style-name next-style))))))))

(defun keiser-odt-d288/transform-dom-to-dom-with-some-colored-paragraphs (dom)
  "fancy-paragraphs"
  (prog1 dom
    (let* ((alist
	    '(("Quotations" . (style:paragraph-properties
			       (
				(fo:border-bottom . "none")
				(fo:border-left . "2.24pt solid #729fcf")
				(fo:border-right . "none")
				(fo:border-top . "none"))))
	      ("First_20_line_20_indent" . (style:text-properties
					    (
					     (fo:color . "#ff8000"))))))
	   (p-styles
	    (odt-dom--query dom %//style:style (string= %style:family "paragraph")
			    (list %style:name %_self))))
      (thread-last p-styles
		   (seq-do
		    (pcase-lambda (`(,style-name ,dom ,paragraph-properties))
		      (pcase style-name
			("Quotations"
			 (let ((paragraph-properties (let-dom dom %/style:paragraph-properties%_first)))
			   (cond
			    (paragraph-properties
			     (let ((props (map-merge 'alist
						     (odt-dom-properties paragraph-properties)
						     (odt-dom-properties (map-elt alist "Quotations")))))
			       (dom-set-attributes paragraph-properties props)))
			    (t (dom-append-child dom (map-elt alist "Quotations"))))))
			("First_20_line_20_indent"
			 (let ((text-properties (let-dom dom %/style:text-properties%_first)))
			   (cond
			    (text-properties
			     (dom-set-attribute text-properties
						'style:text-properties
						(map-merge 'alist
							   text-properties
							   (odt-dom-properties (map-elt "First_20_line_20_indent" alist)))))
			    (t (dom-append-child dom (map-elt alist "First_20_line_20_indent")))))))))))))

(defun keiser-odt-d288/sneak-next-style-names-in-to-paragraph-styles-of-OrgOdtStyles.xml
    (&optional backend odt-styles-file)
  (interactive)
  (kjn-odt-d288/create-custom-styles-from-default-style
   'odt (org-odt-get-backend-property 'odt :styles-file)
   '(
     keiser-odt-d288/tranform-dom-to-the-same-dom
     keiser-odt-d288/transform-dom-to-dom-with-next-style-in-paragraph-styles
     )))

(defun keiser-odt-d288/colorize-QUOTATIONS-and-FIRST-LINE-INDENT (&optional backend odt-styles-file)
  (interactive)
  (kjn-odt-d288/create-custom-styles-from-default-style
   'odt (kjn-odt-d288/infer-styles-file 'odt)
   '(
     keiser-odt-d288/transform-dom-to-dom-with-some-colored-paragraphs
     )))

;;;; [PLACEHOLDER] Does nothing at all

(advice-add 'org-export--collect-tree-properties :around
	    (defun kjn-odt-d288/org-export--collect-tree-properties--around
		(orig-fun &rest orig-args)

	      ;; Ensure that `additional-info' is available to the rest of the parsing machinery
	      (pcase-let* ((`(,data ,info) orig-args))
		;; (message "\n\n\n%S"
		;; 	 `(AT-ENTRY-TO-org-export--collect-tree-properties--around
		;; 	   :info ,(thread-last '(:odt-zip-dir :odt-styles-file :styles-file :input-file
		;; 					      :style-and-next-style)
		;; 			       (seq-mapcat
		;; 				(lambda (it)
		;; 				  (list it (plist-get info it)))))
		;; 	   :backend org-export-current-backend))
		(apply orig-fun orig-args)))
	    )

;; (advice-remove 'org-export--collect-tree-properties 'kjn-odt-d288/org-export--collect-tree-properties--around)

(provide 'odt-d288-1)
;;; odt-d288-1.el ends here
