(setq items
      (->> "/home/kjambunathan/src1/org-mode-ox-odt/testing/examples/odt/Graphics/"
     list
     (--map (directory-files-recursively it (rx (and ".xml" eos)) t))
     (car)
     (--map (cons
	     (file-name-sans-extension (file-name-nondirectory it))
	     (with-current-buffer (find-file-noselect it)
	       (->> (buffer-string)
		    (org-odt--xml-to-lisp)))))
     ;; (--group-by (if (string-match-p "[Ff]rame" (car it))
     ;; 		     "frame"
     ;; 		   "graphics"))

     (--map (cons
	     (car it)

	     (cdr (assq 'style:graphic-properties (cdr it)))  ))

     ;; (-map #'cadr)
     ;; (-flatten-n 1)
     ;; (-map #'car)
     ;; -uniq
     ;; (-sort
     ;;  (lambda (s1 s2)
     ;; 	(string< (symbol-name s1)
     ;; 		 (symbol-name s2))))
     ;; length
     ))

(("Formula"
  ((fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")
   (text:anchor-type . "as-char")))
 ("Frame"
  ((fo:border . "0.06pt solid #000000")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (style:wrap . "parallel")
   (style:wrap-contour . "false")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("Graphics"
  ((style:flow-with-text . "true")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgCaptionedImage"
  ((draw:shadow-opacity . "100%")
   (fo:border . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:min-height . "0cm")
   (fo:padding . "0cm")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:rel-width . "100%")
   (style:run-through . "foreground")
   (style:shadow . "none")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (style:wrap . "none")
   (svg:width . "0cm")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgDisplayFormula"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:number-wrapped-paragraphs . "1")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "run-through")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgDisplayImage"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgFormulaNumberFrame"
  ((draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (fo:background-color . "transparent")
   (fo:border . "none")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:min-height . "0.499cm")
   (fo:padding . "0.15cm")
   (style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (style:wrap . "parallel")
   (style:wrap-contour . "false")
   (svg:width . "2cm")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")))
 ("OrgImageCaptionFrame"
  ((fo:border . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgInlineFormula"
  ((style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")))
 ("OrgInlineImage"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "as-char")))
 ("OrgInlineTaskFrame"
  ((draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (draw:shadow-opacity . "100%")
   (fo:background-color . "#ffffcc")
   (fo:border . "0.26pt solid #000000")
   (fo:padding . "0.15cm")
   (style:background-transparency . "0%")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:shadow . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")))
 ("OrgMarginNote"
  ((draw:shadow-opacity . "100%")
   (fo:border . "none")
   (fo:min-height . "0.041cm")
   (fo:padding . "0cm")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "page-start-margin")
   (style:shadow . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:width . "3cm")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgPageImage"
  ((draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (draw:shadow-opacity . "100%")
   (fo:background-color . "transparent")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-top . "0.21cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:shadow . "none")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "page")))
 ("OrgPageImageCaptionFrame"
  ((draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (draw:shadow-opacity . "100%")
   (fo:background-color . "transparent")
   (fo:border . "none")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:padding . "0cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:shadow . "none")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "paragraph")))
 ("OrgTextBoxFrame"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "char")))
 ("OrgToCharFormula"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "char")))
 ("OrgToCharFormulaCaptionAbove"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "char")))
 ("OrgToCharImage"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "char")))
 ("OrgToCharImageCaptionAbove"
  ((draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (style:wrap . "none")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (text:anchor-type . "char"))))


(setq items
      '(("Formula"
	 ((text:anchor-type . "as-char")
	  (svg:y . "0cm")
	  (fo:margin-left . "0.201cm")
	  (fo:margin-right . "0.201cm")
	  (style:vertical-pos . "middle")
	  (style:vertical-rel . "text")))
	("Frame"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0.201cm")
	  (fo:margin-right . "0.201cm")
	  (fo:margin-top . "0.201cm")
	  (fo:margin-bottom . "0.201cm")
	  (style:wrap . "parallel")
	  (style:number-wrapped-paragraphs . "no-limit")
	  (style:wrap-contour . "false")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph-content")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph-content")
	  (fo:padding . "0.15cm")
	  (fo:border . "0.06pt solid #000000")))
	("Graphics"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")
	  (style:flow-with-text . "true")))
	("OrgCaptionedImage"
	 ((svg:width . "0cm")
	  (style:rel-width . "100%")
	  (fo:min-height . "0cm")
	  (text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0cm")
	  (fo:margin-right . "0cm")
	  (fo:margin-top . "0cm")
	  (fo:margin-bottom . "0cm")
	  (style:run-through . "foreground")
	  (style:wrap . "none")
	  (style:vertical-pos . "from-top")
	  (style:vertical-rel . "paragraph-content")
	  (style:horizontal-pos . "from-left")
	  (style:horizontal-rel . "paragraph-content")
	  (fo:padding . "0cm")
	  (fo:border . "none")
	  (style:shadow . "none")
	  (draw:shadow-opacity . "100%")))
	("OrgDisplayFormula"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:wrap . "run-through")
	  (style:number-wrapped-paragraphs . "1")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")))
	("OrgDisplayImage"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")
	  (draw:wrap-influence-on-position . "once-concurrent")))
	("OrgFormulaNumberFrame"
	 ((svg:width . "2cm")
	  (fo:min-height . "0.499cm")
	  (svg:x . "14.799cm")
	  (svg:y . "0.21cm")
	  (fo:margin-left . "0.201cm")
	  (fo:margin-right . "0.201cm")
	  (fo:margin-top . "0.201cm")
	  (fo:margin-bottom . "0.201cm")
	  (style:wrap . "parallel")
	  (style:number-wrapped-paragraphs . "no-limit")
	  (style:wrap-contour . "false")
	  (style:vertical-pos . "middle")
	  (style:vertical-rel . "paragraph-content")
	  (style:horizontal-pos . "right")
	  (style:horizontal-rel . "paragraph")
	  (fo:background-color . "transparent")
	  (draw:fill . "none")
	  (draw:fill-color . "#729fcf")
	  (fo:padding . "0.15cm")
	  (fo:border . "none")))
	("OrgImageCaptionFrame"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0cm")
	  (fo:margin-right . "0cm")
	  (fo:margin-top . "0cm")
	  (fo:margin-bottom . "0cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")
	  (fo:padding . "0cm")
	  (fo:border . "none")))
	("OrgInlineFormula"
	 ((svg:y . "0cm")
	  (style:vertical-pos . "middle")
	  (style:vertical-rel . "text")))
	("OrgInlineImage"
	 ((text:anchor-type . "as-char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "baseline")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")))
	("OrgInlineTaskFrame"
	 ((svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph-content")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph-content")
	  (fo:background-color . "#ffffcc")
	  (style:background-transparency . "0%")
	  (draw:fill . "solid")
	  (draw:fill-color . "#ffffcc")
	  (draw:opacity . "100%")
	  (fo:padding . "0.15cm")
	  (fo:border . "0.26pt solid #000000")
	  (style:shadow . "none")
	  (draw:shadow-opacity . "100%")))
	("OrgPageImage"
	 ((text:anchor-type . "page")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-top . "0.21cm")
	  (fo:margin-bottom . "0.21cm")
	  (style:vertical-pos . "middle")
	  (style:vertical-rel . "page")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "page")
	  (fo:background-color . "transparent")
	  (draw:fill . "none")
	  (draw:fill-color . "#729fcf")
	  (style:shadow . "none")
	  (draw:shadow-opacity . "100%")))
	("OrgPageImageCaptionFrame"
	 ((text:anchor-type . "paragraph")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0cm")
	  (fo:margin-right . "0cm")
	  (fo:margin-top . "0.21cm")
	  (fo:margin-bottom . "0.21cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "middle")
	  (style:vertical-rel . "page")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "page")
	  (fo:background-color . "transparent")
	  (draw:fill . "none")
	  (draw:fill-color . "#729fcf")
	  (fo:padding . "0cm")
	  (fo:border . "none")
	  (style:shadow . "none")
	  (draw:shadow-opacity . "100%")))
	("OrgTextBoxFrame"
	 ((text:anchor-type . "char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph-content")
	  (draw:wrap-influence-on-position . "once-concurrent")))
	("OrgToCharFormula"
	 ((text:anchor-type . "char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-top . "0.199cm")
	  (fo:margin-bottom . "0.199cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "from-left")
	  (style:horizontal-rel . "paragraph-content")
	  (draw:wrap-influence-on-position . "once-concurrent")))
	("OrgToCharFormulaCaptionAbove"
	 ((text:anchor-type . "char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-top . "0.199cm")
	  (fo:margin-bottom . "0.199cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "bottom")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "from-left")
	  (style:horizontal-rel . "paragraph-content")
	  (draw:wrap-influence-on-position . "once-concurrent")))
	("OrgToCharImage"
	 ((text:anchor-type . "char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0.199cm")
	  (fo:margin-right . "0.199cm")
	  (fo:margin-top . "0.199cm")
	  (fo:margin-bottom . "0.199cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "top")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")
	  (draw:wrap-influence-on-position . "once-concurrent")))
	("OrgToCharImageCaptionAbove"
	 ((text:anchor-type . "char")
	  (svg:x . "0cm")
	  (svg:y . "0cm")
	  (fo:margin-left . "0.199cm")
	  (fo:margin-right . "0.199cm")
	  (fo:margin-top . "0.199cm")
	  (fo:margin-bottom . "0.199cm")
	  (style:wrap . "none")
	  (style:vertical-pos . "bottom")
	  (style:vertical-rel . "paragraph")
	  (style:horizontal-pos . "center")
	  (style:horizontal-rel . "paragraph")
	  (draw:wrap-influence-on-position . "once-concurrent")))))


(("Formula"
  ((text:anchor-type . "as-char")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")))
 ("Frame"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:margin-bottom . "0.201cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (fo:padding . "0.15cm")
   (fo:border . "0.06pt solid #000000")))
 ("Graphics"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:flow-with-text . "true")))
 ("OrgCaptionedImage"
  ((svg:width . "0cm")
   (style:rel-width . "100%")
   (fo:min-height . "0cm")
   (text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:margin-bottom . "0cm")
   (style:run-through . "foreground")
   (style:wrap . "none")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (fo:padding . "0cm")
   (fo:border . "none")
   (style:shadow . "none")
   (draw:shadow-opacity . "100%")))
 ("OrgDisplayFormula"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "run-through")
   (style:number-wrapped-paragraphs . "1")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")))
 ("OrgDisplayImage"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgFormulaNumberFrame"
  ((svg:width . "2cm")
   (fo:min-height . "0.499cm")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:margin-bottom . "0.201cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (fo:padding . "0.15cm")
   (fo:border . "none")))
 ("OrgImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:margin-bottom . "0cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (fo:padding . "0cm")
   (fo:border . "none")))
 ("OrgInlineFormula"
  ((svg:y . "0cm")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")))
 ("OrgInlineImage"
  ((text:anchor-type . "as-char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")))
 ("OrgInlineTaskFrame"
  ((svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (fo:background-color . "#ffffcc")
   (style:background-transparency . "0%")
   (draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (fo:padding . "0.15cm")
   (fo:border . "0.26pt solid #000000")
   (style:shadow . "none")
   (draw:shadow-opacity . "100%")))
 ("OrgPageImage"
  ((text:anchor-type . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:margin-bottom . "0.21cm")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (style:shadow . "none")
   (draw:shadow-opacity . "100%")))
 ("OrgPageImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:margin-bottom . "0.21cm")
   (style:wrap . "none")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")
   (fo:padding . "0cm")
   (fo:border . "none")
   (style:shadow . "none")
   (draw:shadow-opacity . "100%")))
 ("OrgTextBoxFrame"
  ((text:anchor-type . "char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharFormula"
  ((text:anchor-type . "char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-top . "0.199cm")
   (fo:margin-bottom . "0.199cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharFormulaCaptionAbove"
  ((text:anchor-type . "char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-top . "0.199cm")
   (fo:margin-bottom . "0.199cm")
   (style:wrap . "none")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharImage"
  ((text:anchor-type . "char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")
   (fo:margin-bottom . "0.199cm")
   (style:wrap . "none")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharImageCaptionAbove"
  ((text:anchor-type . "char")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")
   (fo:margin-bottom . "0.199cm")
   (style:wrap . "none")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (draw:wrap-influence-on-position . "once-concurrent"))))

(setq all-props-with-values
      (->> items
	   (-map #'cadr)
	   (-flatten-n 1)
	   ;; (-map 'car)
	   ;; -uniq
	   ;; (-sort
	   ;;  (lambda (s1 s2)
	   ;;    (string< (symbol-name s1)
	   ;; 	       (symbol-name s2))))
	   (-group-by 'car)
	   (--map (cons
		   (car it)
		   (->> (cdr it)
			(-map 'cdr)
			-uniq
			(-sort #'string<))))
	   (-sort
	    (lambda (s1 s2)
	      (string< (symbol-name (car s1))
		       (symbol-name (car s2)))))
	   ))
((draw:fill "none" "solid")
 (draw:fill-color "#729fcf" "#ffffcc")
 (draw:opacity "100%")
 (draw:shadow-opacity "100%")
 (draw:wrap-influence-on-position "once-concurrent")
 (fo:background-color "#ffffcc" "transparent")
 (fo:border "0.06pt solid #000000" "0.26pt solid #000000" "none")
 (fo:margin-bottom "0.199cm" "0.201cm" "0.21cm" "0cm")
 (fo:margin-left "0.199cm" "0.201cm" "0cm")
 (fo:margin-right "0.199cm" "0.201cm" "0cm")
 (fo:margin-top "0.199cm" "0.201cm" "0.21cm" "0cm")
 (fo:min-height "0.041cm" "0.499cm" "0cm")
 (fo:padding "0.15cm" "0cm")
 (style:background-transparency "0%")
 (style:flow-with-text "true")
 (style:horizontal-pos "center" "from-left" "right")
 (style:horizontal-rel "page" "page-start-margin" "paragraph" "paragraph-content")
 (style:number-wrapped-paragraphs "1" "no-limit")
 (style:rel-width "100%")
 (style:run-through "foreground")
 (style:shadow "none")
 (style:vertical-pos "bottom" "from-top" "middle" "top")
 (style:vertical-rel "baseline" "page" "paragraph" "paragraph-content" "text")
 (style:wrap "none" "parallel" "run-through")
 (style:wrap-contour "false")
 (svg:width "0cm" "2cm" "3cm")
 (svg:x "0cm" "14.799cm")
 (svg:y "0.21cm" "0cm")
 (text:anchor-type "as-char" "char" "page" "paragraph"))


(setq all-props
      (->> all-props-with-values
	   (-map 'car)))

(draw:fill draw:fill-color draw:opacity draw:shadow-opacity draw:wrap-influence-on-position fo:background-color fo:border fo:margin-bottom fo:margin-left fo:margin-right fo:margin-top fo:min-height fo:padding style:background-transparency style:flow-with-text style:horizontal-pos style:horizontal-rel style:number-wrapped-paragraphs style:rel-width style:run-through style:shadow style:vertical-pos style:vertical-rel style:wrap style:wrap-contour svg:width svg:x svg:y text:anchor-type)


(->> all-props
     length)
29 (#o35, #x1d, ?\C-\])


(setq props-order
      '(
	;; Type
	text:anchor-type
	style:horizontal-pos
	style:horizontal-rel
	style:vertical-pos
	style:vertical-rel
	svg:x
	svg:y
	fo:min-height
	style:rel-width
	svg:width
	style:flow-with-text
	;; Wrap
	style:wrap
	draw:wrap-influence-on-position
	style:number-wrapped-paragraphs
	style:wrap-contour
	fo:margin-bottom
	fo:margin-left
	fo:margin-right
	fo:margin-top
	;; Borders
	fo:padding
	fo:border
	draw:shadow-opacity
	style:shadow
	;; Area
	fo:background-color
	draw:fill
	draw:fill-color
	draw:opacity
	;; Transparency
	style:background-transparency
	;; Don't know
	style:run-through))
(text:anchor-type style:horizontal-pos style:horizontal-rel style:vertical-pos style:vertical-rel svg:x svg:y fo:min-height style:rel-width svg:width style:flow-with-text style:wrap draw:wrap-influence-on-position style:number-wrapped-paragraphs style:wrap-contour fo:margin-bottom fo:margin-left fo:margin-right fo:margin-top fo:padding fo:border draw:shadow-opacity style:shadow fo:background-color draw:fill draw:fill-color draw:opacity style:background-transparency style:run-through)


(setq result
      (cl-loop for item in items
	       for name = (car item)
	       for props = (cadr item)
	       do (message "props: %S" props)
	       collect (list name
			     (cl-loop for key in props-order
				      for val = (assq key props)
				      when val
				      collect val))))
(("Formula"
  ((text:anchor-type . "as-char")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")))
 ("Frame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "0.06pt solid #000000")))
 ("Graphics"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:flow-with-text . "true")
   (style:wrap . "none")))
 ("OrgCaptionedImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:min-height . "0cm")
   (style:rel-width . "100%")
   (svg:width . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (style:run-through . "foreground")))
 ("OrgDisplayFormula"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "run-through")
   (style:number-wrapped-paragraphs . "1")))
 ("OrgDisplayImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgFormulaNumberFrame"
  ((style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")
   (fo:min-height . "0.499cm")
   (svg:width . "2cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")))
 ("OrgInlineFormula"
  ((style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")))
 ("OrgInlineImage"
  ((text:anchor-type . "as-char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (svg:x . "0cm")
   (svg:y . "0cm")))
 ("OrgInlineTaskFrame"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:padding . "0.15cm")
   (fo:border . "0.26pt solid #000000")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "#ffffcc")
   (draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (style:background-transparency . "0%")))
 ("OrgMarginNote"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "page-start-margin")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:min-height . "0.041cm")
   (svg:width . "3cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")))
 ("OrgPageImage"
  ((text:anchor-type . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-top . "0.21cm")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgPageImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgTextBoxFrame"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharFormula"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharFormulaCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImage"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImageCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm"))))




(cl-loop for key in props-order
	 for val = (assq key all-props-with-values)
	 when val
	 collect (car val))

(text:anchor-type
 style:horizontal-pos
 style:horizontal-rel
 style:vertical-pos
 style:vertical-rel
 svg:x
 svg:y
 fo:min-height
 style:rel-width
 svg:width
 style:flow-with-text
 style:wrap
 draw:wrap-influence-on-position
 style:number-wrapped-paragraphs
 style:wrap-contour
 fo:margin-bottom
 fo:margin-left
 fo:margin-right
 fo:margin-top
 fo:padding
 fo:border
 draw:shadow-opacity
 style:shadow
 fo:background-color
 draw:fill
 draw:fill-color
 draw:opacity
 style:background-transparency
 style:run-through
 )









(
 ;;  "as-char" "char" "page" "paragraph"
 (text:anchor-type ,anchor-type)
 ;;  "center" "from-left" "right"
 (style:horizontal-pos ,horizontal-pos)
 ;;  "page" "paragraph" "paragraph-content"
 (style:horizontal-rel ,horizontal-rel)
 ;;  "bottom" "from-top" "middle" "top"
 (style:vertical-pos ,vertical-pos)
 ;;  "baseline" "page" "paragraph" "paragraph-content" "text"
 (style:vertical-rel ,vertical-rel)
 ;;  "0cm" "14.799cm"
 (svg:x ,x)
 ;;  "0.21cm" "0cm"
 (svg:y ,y)
 ;;  "0.499cm" "0cm"
 (fo:min-height ,min-height)
 ;;  "100%"
 (style:rel-width ,rel-width)
 ;;  "0cm" "2cm"
 (svg:width ,width)
 ;;  "true"
 (style:flow-with-text ,flow-with-text)
 ;;  "none" "parallel" "run-through"
 (style:wrap ,wrap)
 ;;  "once-concurrent"
 (draw:wrap-influence-on-position ,wrap-influence-on-position)
 ;;  "1" "no-limit"
 (style:number-wrapped-paragraphs ,number-wrapped-paragraphs)
 ;;  "false"
 (style:wrap-contour ,wrap-contour)
 ;;  "0.199cm" "0.201cm" "0.21cm" "0cm"
 (fo:margin-bottom ,margin-bottom)
 ;;  "0.199cm" "0.201cm" "0cm"
 (fo:margin-left ,margin-left)
 ;;  "0.199cm" "0.201cm" "0cm"
 (fo:margin-right ,margin-right)
 ;;  "0.199cm" "0.201cm" "0.21cm" "0cm"
 (fo:margin-top ,margin-top)
 ;;  "0.15cm" "0cm"
 (fo:padding ,padding)
 ;;  "0.06pt solid #000000" "0.26pt solid #000000" "none"
 (fo:border ,border)
 ;;  "100%"
 (draw:shadow-opacity ,shadow-opacity)
 ;;  "none"
 (style:shadow ,shadow)
 ;;  "#ffffcc" "transparent"
 (fo:background-color ,background-color)
 ;;  "none" "solid"
 (draw:fill ,fill)
 ;;  "#729fcf" "#ffffcc"
 (draw:fill-color ,fill-color)
 ;;  "100%"
 (draw:opacity ,opacity)
 ;;  "0%"
 (style:background-transparency ,background-transparency)
 ;;  "foreground"
 (style:run-through ,run-through))





(->> result
     (-sort
      (lambda (s1 s2)
	(< (length (cadr s1))
	   (length (cadr s2))))))

(("OrgInlineFormula"
  ((style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")))
 ("Formula"
  ((text:anchor-type . "as-char")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")))
 ("OrgInlineImage"
  ((text:anchor-type . "as-char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (svg:x . "0cm")
   (svg:y . "0cm")))
 ("Graphics"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:flow-with-text . "true")
   (style:wrap . "none")))
 ("OrgDisplayFormula"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "run-through")
   (style:number-wrapped-paragraphs . "1")))
 ("OrgDisplayImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgTextBoxFrame"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharFormula"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharFormulaCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImage"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImageCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")))
 ("OrgPageImage"
  ((text:anchor-type . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-top . "0.21cm")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("Frame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "0.06pt solid #000000")))
 ("OrgInlineTaskFrame"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:padding . "0.15cm")
   (fo:border . "0.26pt solid #000000")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "#ffffcc")
   (draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (style:background-transparency . "0%")))
 ("OrgPageImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgCaptionedImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:min-height . "0cm")
   (style:rel-width . "100%")
   (svg:width . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (style:run-through . "foreground")))
 ("OrgFormulaNumberFrame"
  ((style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")
   (fo:min-height . "0.499cm")
   (svg:width . "2cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf"))))


(("OrgCaptionedImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:min-height . "0cm")
   (style:rel-width . "100%")
   (svg:width . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (style:run-through . "foreground")))
 ("OrgFormulaNumberFrame"
  ((style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")
   (fo:min-height . "0.499cm")
   (svg:width . "2cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgPageImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("Frame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "0.06pt solid #000000")))
 ("OrgInlineTaskFrame"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:padding . "0.15cm")
   (fo:border . "0.26pt solid #000000")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "#ffffcc")
   (draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (style:background-transparency . "0%")))
 ("OrgImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")))
 ("OrgPageImage"
  ((text:anchor-type . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-top . "0.21cm")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgToCharImage"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImageCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharFormula"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharFormulaCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("Graphics"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:flow-with-text . "true")
   (style:wrap . "none")))
 ("OrgDisplayFormula"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "run-through")
   (style:number-wrapped-paragraphs . "1")))
 ("OrgDisplayImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgTextBoxFrame"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgInlineImage"
  ((text:anchor-type . "as-char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (svg:x . "0cm")
   (svg:y . "0cm")))
 ("Formula"
  ((text:anchor-type . "as-char")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")))
 ("OrgInlineFormula"
  ((style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm"))))

(("Formula"
  ((text:anchor-type . "as-char")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")))
 ("Frame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "0.06pt solid #000000")))
 ("Graphics"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:flow-with-text . "true")
   (style:wrap . "none")))
 ("OrgCaptionedImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "from-top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:min-height . "0cm")
   (style:rel-width . "100%")
   (svg:width . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (style:run-through . "foreground")))
 ("OrgDisplayFormula"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "run-through")
   (style:number-wrapped-paragraphs . "1")))
 ("OrgDisplayImage"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgFormulaNumberFrame"
  ((style:horizontal-pos . "right")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "14.799cm")
   (svg:y . "0.21cm")
   (fo:min-height . "0.499cm")
   (svg:width . "2cm")
   (style:wrap . "parallel")
   (style:number-wrapped-paragraphs . "no-limit")
   (style:wrap-contour . "false")
   (fo:margin-bottom . "0.201cm")
   (fo:margin-left . "0.201cm")
   (fo:margin-right . "0.201cm")
   (fo:margin-top . "0.201cm")
   (fo:padding . "0.15cm")
   (fo:border . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0cm")
   (fo:padding . "0cm")
   (fo:border . "none")))
 ("OrgInlineFormula"
  ((style:vertical-pos . "middle")
   (style:vertical-rel . "text")
   (svg:y . "0cm")))
 ("OrgInlineImage"
  ((text:anchor-type . "as-char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "baseline")
   (svg:x . "0cm")
   (svg:y . "0cm")))
 ("OrgInlineTaskFrame"
  ((style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph-content")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:padding . "0.15cm")
   (fo:border . "0.26pt solid #000000")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "#ffffcc")
   (draw:fill . "solid")
   (draw:fill-color . "#ffffcc")
   (draw:opacity . "100%")
   (style:background-transparency . "0%")))
 ("OrgPageImage"
  ((text:anchor-type . "page")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-top . "0.21cm")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgPageImageCaptionFrame"
  ((text:anchor-type . "paragraph")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "page")
   (style:vertical-pos . "middle")
   (style:vertical-rel . "page")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (fo:margin-bottom . "0.21cm")
   (fo:margin-left . "0cm")
   (fo:margin-right . "0cm")
   (fo:margin-top . "0.21cm")
   (fo:padding . "0cm")
   (fo:border . "none")
   (draw:shadow-opacity . "100%")
   (style:shadow . "none")
   (fo:background-color . "transparent")
   (draw:fill . "none")
   (draw:fill-color . "#729fcf")))
 ("OrgTextBoxFrame"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")))
 ("OrgToCharFormula"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharFormulaCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "from-left")
   (style:horizontal-rel . "paragraph-content")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImage"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "top")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm")))
 ("OrgToCharImageCaptionAbove"
  ((text:anchor-type . "char")
   (style:horizontal-pos . "center")
   (style:horizontal-rel . "paragraph")
   (style:vertical-pos . "bottom")
   (style:vertical-rel . "paragraph")
   (svg:x . "0cm")
   (svg:y . "0cm")
   (style:wrap . "none")
   (draw:wrap-influence-on-position . "once-concurrent")
   (fo:margin-bottom . "0.199cm")
   (fo:margin-left . "0.199cm")
   (fo:margin-right . "0.199cm")
   (fo:margin-top . "0.199cm"))))



(->> items
     (--map (cons (car it)
		  (length (cadr it)))))

(->> result
     (--map (cons (car it)
		  (length (cadr it)))))

(("Formula" . 6)
 ("Frame" . 16)
 ("Graphics" . 9)
 ("OrgCaptionedImage" . 20)
 ("OrgDisplayFormula" . 9)
 ("OrgDisplayImage" . 9)
 ("OrgFormulaNumberFrame" . 20)
 ("OrgImageCaptionFrame" . 14)
 ("OrgInlineFormula" . 3)
 ("OrgInlineImage" . 7)
 ("OrgInlineTaskFrame" . 16)
 ("OrgPageImage" . 14)
 ("OrgPageImageCaptionFrame" . 19)
 ("OrgTextBoxFrame" . 9)
 ("OrgToCharFormula" . 11)
 ("OrgToCharFormulaCaptionAbove" . 11)
 ("OrgToCharImage" . 13)
 ("OrgToCharImageCaptionAbove" . 13))



(("Formula" . 6)
 ("Frame" . 16)
 ("Graphics" . 9)
 ("OrgCaptionedImage" . 20)
 ("OrgDisplayFormula" . 9)
 ("OrgDisplayImage" . 9)
 ("OrgFormulaNumberFrame" . 20)
 ("OrgImageCaptionFrame" . 14)
 ("OrgInlineFormula" . 3)
 ("OrgInlineImage" . 7)
 ("OrgInlineTaskFrame" . 16)
 ("OrgPageImage" . 14)
 ("OrgPageImageCaptionFrame" . 19)
 ("OrgTextBoxFrame" . 9)
 ("OrgToCharFormula" . 11)
 ("OrgToCharFormulaCaptionAbove" . 11)
 ("OrgToCharImage" . 13)
 ("OrgToCharImageCaptionAbove" . 13))









((draw:fill "none" "solid")
 (draw:fill-color "#729fcf" "#ffffcc")
 (draw:opacity "100%")
 (draw:shadow-opacity "100%")
 (draw:wrap-influence-on-position "once-concurrent")
 (fo:background-color "#ffffcc" "transparent")
 (fo:border "0.06pt solid #000000" "0.26pt solid #000000" "none")
 (fo:margin-bottom "0.199cm" "0.201cm" "0.21cm" "0cm")
 (fo:margin-left "0.199cm" "0.201cm" "0cm")
 (fo:margin-right "0.199cm" "0.201cm" "0cm")
 (fo:margin-top "0.199cm" "0.201cm" "0.21cm" "0cm")
 (fo:min-height "0.499cm" "0cm")
 (fo:padding "0.15cm" "0cm")
 (style:background-transparency "0%")
 (style:flow-with-text "true")
 (style:horizontal-pos "center" "from-left" "right")
 (style:horizontal-rel "page" "paragraph" "paragraph-content")
 (style:number-wrapped-paragraphs "1" "no-limit")
 (style:rel-width "100%")
 (style:run-through "foreground")
 (style:shadow "none")
 (style:vertical-pos "bottom" "from-top" "middle" "top")
 (style:vertical-rel "baseline" "page" "paragraph" "paragraph-content" "text")
 (style:wrap "none" "parallel" "run-through")
 (style:wrap-contour "false")
 (svg:width "0cm" "2cm")
 (svg:x "0cm" "14.799cm")
 (svg:y "0.21cm" "0cm")
 (text:anchor-type "as-char" "char" "page" "paragraph"))

(cl-loop for key in '(
		      svg:x
		      svg:y
		      fo:min-height
		      style:rel-width
		      svg:width
		      text:anchor-type
		      style:vertical-pos
		      style:vertical-rel
		      style:horizontal-pos
		      style:horizontal-rel
		      style:flow-with-text
		      fo:margin-bottom
		      fo:margin-left
		      fo:margin-right
		      fo:margin-top
		      style:number-wrapped-paragraphs
		      style:wrap
		      draw:wrap-influence-on-position
		      fo:border
		      fo:padding
		      style:shadow
		      draw:fill
		      draw:fill-color
		      draw:shadow-opacity
		      fo:background-color
		      style:run-through)
	 for val = (assq key all)
	 when val
	 collect val)
